### ISSUE TITLE
script in wiki can't work

### ISSUE THREAD

**Issue by cyber-nova** [moecube/srvpro#17]
the script in wiki for Ubuntu 18
``npm WARN saveError ENOENT: no such file or directory, open '/root/package.json'
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN enoent ENOENT: no such file or directory, open '/root/package.json'
npm WARN root No description
npm WARN root No repository field.
npm WARN root No README data
npm WARN root No license field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.7 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.7: wanted {"os":"darwin","arch":"any"} (current: `{"os":"linux","arch":"x64"})`

how to fix it

**Comment by purerosefallen** [comment]
The working directory may be incorrect. Please run `npm install` in the your directory of srvpro. In script it should be `~/ygopro-server`, or `/root/ygopro-server` on your machine.

**Comment by cyber-nova** [comment]
thanks for help. finally i install it successfully but when i use it it stops after show some information 
> # node ygopro-server.jsver
{"name":"mycard","hostname":"vultr.guest","pid":11508,"level":30,"msg":"ygopro version 0x1342 (from config)","time":"2019-02-26T08:36:13.983Z","v":0}
{"name":"mycard","hostname":"vultr.guest","pid":11508,"level":30,"msg":"server started 7911","time":"2019-02-26T08:36:14.042Z","v":0}
{"name":"mycard","hostname":"vultr.guest","pid":11508,"level":30,"msg":"dialogues loaded 329","time":"2019-02-26T08:36:14.204Z","v":0}
how to continue

**Comment by cyber-nova** [comment]
thanks for help, but 
ln: failed to create symbolic link '.'$'\r': File exists
ln: failed to create symbolic link '.'$'\r': File exists
mkdir: cannot create directory ‘config\r’: File exists
cp: cannot create regular file 'config/config.json'$'\r': No such file or directory
which files should be removed

**Comment by purerosefallen** [comment]
Not every of the 4 `ln`s are really necessary. Depending on your OS, only 2 of them are needed. So ignore the errors from `ln`.
For the config, just keep the directory created, and place `data/default_config.json` into `config/config.json`. If exists, just edit it as you like.
