### ISSUE TITLE
It seems that server forgot to send duel_rule in MSG_START when client reconnecting

### ISSUE THREAD

**Issue by WolcenSykes** [moecube/srvpro#19]
Although this didn't trigger any crash of client, but I think this is a kind of bug, after all the LP on client would be undefined value during few milliseconds when client resolving the wrong MSG_START. 
Just mention it tentatively.

**Comment by purerosefallen** [comment]
Please update the ygopro server executable on your server.

**Comment by WolcenSykes** [comment]
sorry, my fault, you did fix that
